# Generated by Django 3.1.4 on 2020-12-15 17:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('ip', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('karma', models.IntegerField()),
                ('approved', models.CharField(max_length=250)),
                ('agent', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asenzor.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('type', models.CharField(max_length=250, verbose_name='Tipo')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=250, verbose_name='Titulo')),
                ('excerpt', models.TextField()),
                ('status', models.CharField(max_length=250, verbose_name='Estatus')),
                ('comment_status', models.CharField(max_length=250)),
                ('ping_status', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('modified', models.DateTimeField(max_length=250)),
                ('content_filtered', models.TextField(max_length=250)),
                ('guid', models.CharField(max_length=250)),
                ('menu_order', models.IntegerField()),
                ('mime_type', models.CharField(max_length=250)),
                ('comment_count', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asenzor.post')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('domain', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('group', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250)),
                ('value', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TermTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('count', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asenzor.termtaxonomy')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asenzor.term')),
            ],
        ),
        migrations.CreateModel(
            name='PostMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250)),
                ('value', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asenzor.post')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.TextField()),
                ('autoload', models.CharField(max_length=250)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asenzor.site')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('target', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('visible', models.CharField(max_length=250)),
                ('raiting', models.IntegerField()),
                ('updated', models.DateTimeField()),
                ('rel', models.CharField(max_length=250)),
                ('notes', models.TextField()),
                ('rss', models.CharField(max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250)),
                ('value', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asenzor.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asenzor.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
