# Generated by Django 3.1.4 on 2020-12-22 02:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('asenzor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='fields',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment_status',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='menu_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mime_type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asenzor.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ping_status',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(max_length=250, null=True, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Entrada', 'post'), ('Pagina', 'page'), ('Formulario', 'form'), ('Medio', 'atachment')], max_length=250, verbose_name='Tipo'),
        ),
    ]
