# Generated by Django 3.1.4 on 2020-12-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asenzor', '0002_auto_20201222_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='master',
            field=models.BooleanField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='autoload',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
