# Generated by Django 3.1.4 on 2021-01-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asenzor', '0005_auto_20201230_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='description',
            field=models.TextField(blank=True, help_text='Este campo sera util para cuando se definen las opciones\n\t\tde forma personalizada, ya que asi tenemos una descripcion rapida para \n\t\tque puede servir si se nos olvida', null=True),
        ),
        migrations.AddField(
            model_name='postmeta',
            name='description',
            field=models.TextField(blank=True, help_text='Este campo sera util para cuando se definen los metadatos\n\t\tde forma personalizada, ya que asi tenemos una descripcion rapida para \n\t\tque puede servir si se nos olvida', null=True),
        ),
        migrations.AddField(
            model_name='usermeta',
            name='description',
            field=models.TextField(blank=True, help_text='Este campo sera util para cuando se definen los metadatos\n\t\tde forma personalizada, ya que asi tenemos una descripcion rapida para \n\t\tque puede servir si se nos olvida', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
