# Generated by Django 3.1.4 on 2021-01-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asenzor', '0007_auto_20210109_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmeta',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermeta',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
