# Generated by Django 3.1.4 on 2021-02-03 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asenzor', '0009_usermeta_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, default='public', max_length=250, null=True, verbose_name='Estatus'),
        ),
    ]
