# Generated by Django 3.1.4 on 2021-02-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asenzor', '0010_auto_20210203_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='guid',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
